version: '3.5'
services:
    express:
        container_name: express
        build:
            dockerfile: docker/express/Dockerfile
            context: .
        depends_on:
            - postgres
        ports:
            - ${PORT}:${PORT}
        volumes:
            - ${EXPRESS_DIR_SRC}:/usr/app/src
            - ${EXPRESS_DIR_TEST}:/usr/app/test
            - ${EXPRESS_DIR_LOGS}:/usr/app/logs
            - ${EXPRESS_DIR_DOC}:/usr/app/doc
        networks:
            - custom-network
        restart: always
    postgres:
        container_name: postgres
        build:
            dockerfile: docker/postgres/Dockerfile
            context: .
        ports:
            - ${PG_PORT}:${PG_PORT}
        environment:
            POSTGRES_USER: ${PG_USER}
            POSTGRES_PASSWORD: ${PG_PASS}
            POSTGRES_DB: ${PG_DB}
            PGDATA: /var/lib/pg_data
        networks:
            - custom-network
        restart: always
        volumes:
            - ${PG_DATA}:/var/lib/pg_data
networks:
    custom-network:
        name: custom-network
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${SUBNET}